{"uuid":"7231ccb7-bffa-4fba-b105-49984c476269","historyId":"6ef8fc5025d8005b7b7a6695c65bffc1","fullName":"tests.AppiumTest.appiumTest1","labels":[{"name":"package","value":"tests.AppiumTest"},{"name":"testClass","value":"tests.AppiumTest"},{"name":"testMethod","value":"appiumTest1"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"cross-platform-appium"},{"name":"subSuite","value":"tests.AppiumTest"},{"name":"host","value":"192.168.1.13.non-exists.ptr.local"},{"name":"thread","value":"52093@192.168.1.13.non-exists.ptr.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"appiumTest1","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.\nNode.js executable path: /Users/haneulpham/.nvm/versions/node/v22.4.1/bin/node\nArguments: [/Users/haneulpham/.nvm/versions/node/v22.4.1/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 127.0.0.1, --log-level, info, --session-override]\nServer log: \u001B[38;5;112m[Appium]\u001B[0m Welcome to Appium v2.12.1 (REV 8fbf8ab6943d0bcb402773c3c2b30c2f103d7fa2)\n\u001B[38;5;112m[Appium]\u001B[0m Non-default server args:\n\u001B[38;5;112m[Appium]\u001B[0m { address: \u001B[32m'127.0.0.1'\u001B[39m, loglevel: \u001B[32m'info'\u001B[39m, sessionOverride: \u001B[33mtrue\u001B[39m }\n\u001B[38;5;112m[Appium]\u001B[0m Attempting to load driver uiautomator2...\n\u001B[38;5;112m[Appium]\u001B[0m Attempting to load driver xcuitest...\n\u001B[38;5;112m[Appium]\u001B[0m Attempting to load driver espresso...\n\u001B[38;5;86m[HTTP]\u001B[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\n\u001B[38;5;112m[Appium]\u001B[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723\n","trace":"io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.\nNode.js executable path: /Users/haneulpham/.nvm/versions/node/v22.4.1/bin/node\nArguments: [/Users/haneulpham/.nvm/versions/node/v22.4.1/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 127.0.0.1, --log-level, info, --session-override]\nServer log: \u001B[38;5;112m[Appium]\u001B[0m Welcome to Appium v2.12.1 (REV 8fbf8ab6943d0bcb402773c3c2b30c2f103d7fa2)\n\u001B[38;5;112m[Appium]\u001B[0m Non-default server args:\n\u001B[38;5;112m[Appium]\u001B[0m { address: \u001B[32m'127.0.0.1'\u001B[39m, loglevel: \u001B[32m'info'\u001B[39m, sessionOverride: \u001B[33mtrue\u001B[39m }\n\u001B[38;5;112m[Appium]\u001B[0m Attempting to load driver uiautomator2...\n\u001B[38;5;112m[Appium]\u001B[0m Attempting to load driver xcuitest...\n\u001B[38;5;112m[Appium]\u001B[0m Attempting to load driver espresso...\n\u001B[38;5;86m[HTTP]\u001B[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\n\u001B[38;5;112m[Appium]\u001B[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723\n\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:192)\n\tat base.AppiumServerManager.startServer(AppiumServerManager.java:30)\n\tat tests.AppiumTest.appiumTest1(AppiumTest.java:49)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\n\tat org.testng.TestRunner.run(TestRunner.java:614)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\n\tat org.testng.TestNG.run(TestNG.java:1079)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\nCaused by: io.appium.java_client.service.local.AppiumServerAvailabilityChecker$ConnectionTimeout: ConnectionTimeout\n\tat io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:72)\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:144)\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:185)\n\t... 27 more\nCaused by: java.net.ConnectException: Connection refused\n\tat java.base/sun.nio.ch.Net.pollConnect(Native Method)\n\tat java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)\n\tat java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)\n\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)\n\tat java.base/java.net.Socket.connect(Socket.java:760)\n\tat java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)\n\tat java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)\n\tat java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)\n\tat java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)\n\tat java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)\n\tat java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)\n\tat java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1310)\n\tat java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1243)\n\tat java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1129)\n\tat java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1058)\n\tat io.appium.java_client.service.local.AppiumServerAvailabilityChecker.connectToUrl(AppiumServerAvailabilityChecker.java:79)\n\tat io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:61)\n\t... 29 more\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1734347613522,"stop":1734347633825}